variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_DRIVER: overlay
  KUBE_NAMESPACE: "msprci-${CI_BUILD_REF_NAME}"

stages:
  - build
  - test
  - dockerbuild
  - sonar
  - deploy
  - end2end

cache:
  paths:
    - node_modules/
    - coverage/

build:
  stage: build
  image: node:12.16.0-alpine3.11
  script:
    - rm -rf coverage
    - npm install
    - npm run build

test:
  stage: test
  image: node:12.16.0-alpine3.11
  script: CI=true npm test -- --coverage
  after_script:
    - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls

dockerbuild:
  extends: .template-docker-build
  variables:
    API_URL: http://api.highlander.fail
  only:
    - /master/

dockerbuild-develop:
  extends: .template-docker-build
  variables:
    API_URL: http://api.develop.highlander.fail
  only:
    - /developp/

dockerbuild-release:
  extends: .template-docker-build
  variables:
    API_URL: http://api.release.highlander.fail
  only:
    - /^release-.*/

.template-docker-build:
  stage: dockerbuild
  image: docker:19.03.1
  services:
    - docker:19.03.1-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest . --build-arg API_URL=$API_URL
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest

sonar:
  stage: sonar
  image:
    name: sonarsource/sonar-scanner-cli:4.2
    entrypoint: [""]
  variables:
    SONAR_TOKEN: $SONAR_TOKEN
    SONAR_HOST_URL: $SONAR_HOST_URL
    GIT_DEPTH: 0
  script: sonar-scanner -Dsonar.projectKey=$SONAR_PROJECT -Dsonar.branch.name=${CI_BUILD_REF_NAME} -Dsonar.organization=$SONAR_ORGANIZATION
  only:
    - /develop/
    - /master/

deploy-release:
  stage: deploy
  image: hublo/kubectl:latest
  script:
    - echo -n $KUBE_CONFIG | base64 -d > ./config
    - kubectl set image deployment/highlanderfront $CONTAINER_NAME=$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --kubeconfig ./config --namespace msprci-release
  only:
    - /^release-.*/

deploy:
  stage: deploy
  image: hublo/kubectl:latest
  script:
    - echo -n $KUBE_CONFIG | base64 -d > ./config
    - kubectl set image deployment/highlanderfront $CONTAINER_NAME=$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --kubeconfig ./config --namespace $KUBE_NAMESPACE
  only:
    - develop
    - master

end-2-end:
  stage: end2end
  image: cypress/base:10
  script:
    - npm run cy:verify
    - npm run test:cypress
  artifacts:
    paths:
      - cypress/videos
      - cypress/screenshots
    expire_in: 1 day
  only:
    - /^release-.*/
